### ISSUE TITLE
Add filtering to only show a single specific style

### ISSUE THREAD

**Issue by rmzelle** [zotero/styles-repo#11]
We all seem to like the ability to point users to certain styles in the repo: https://forums.zotero.org/search/?PostBackAction=Search&Keywords=styles%3Fq&Type=Comments&btnSubmit=Search .

My issue is that it's sometimes impossible to highlight a certain style, e.g. https://zotero.org/styles?q=vancouver lists 17 styles, while I might only want to select "Vancouver". I could direct users directly to "https://zotero.org/styles/vancouver" or "https://zotero.org/styles/vancouver?source=1", but that doesn't provide as much context. Would it make sense to support the standard regex "^" and "$" characters, so we can search for "^Vancouver$" and only get one hit?

Alternatively we could use a flag for "exact match".

cc @aurimasv, @adam3smith

**Comment by rmzelle** [comment]
Coming back to this, @dstillman, how would you feel about `https://www.zotero.org/styles?id=apa` as a way to target a single style? (`id=apa` would match apa.csl)

That certainly seems like the most concise option. I was also thinking that, when the page is loaded with the "id" URL parameter, it might make sense to fill the search field with something like "id=apa" or "apa[id]" (this latter option is similar to PubMed searches: http://www.ncbi.nlm.nih.gov/pubmed/?term=Zelle+RM%5BAuthor%5D ). Then, if the user changes the contents of the search field to some other string, the URL "id" parameter would be removed.

**Comment by dstillman** [comment]
I think a colon makes the most sense in the field: ``id:apa``. (This is similar to various keywords in Google search, like `site:`.) And we can get that for free with ``q=id:apa``. We can fix the code to not swap in a ``%3A`` for the colon.

**Comment by rmzelle** [comment]
Works for me.

(is there an easy way to hack on this project without installing all the prerequisites like apache listed in https://github.com/zotero/styles-repo/blob/master/README.md?)

**Comment by rmzelle** [comment]
@tnajdek, is this in the cards for the revamped version? Would be much appreciated.

**Comment by tnajdek** [comment]
I'd be happy to make this happen, just thought of a bit different approach. My suggestion would be to use fragment identifier to highlight matching style in the results. This means we could do the following:

https://www.zotero.org/styles?q=apa#apa

This would produce the same results as it does currently, however it would highlight second row of results and (optionally) automatically scroll to that result, something similar looking to this:

<img width="956" alt="screen shot 2016-05-02 at 14 37 52" src="https://cloud.githubusercontent.com/assets/214628/14955685/954aee84-1073-11e6-8db5-02bc8e5f5dcb.png">

Would that be a good solution?

**Comment by rmzelle** [comment]
I guess. I still would prefer a solution that would allow us to point to one style, and one style only, though.

Ideally it would also be very easy for us to fashion such a targeted URL (e.g. from the source link, "https://www.zotero.org/styles/3-biotech?source=1"), so the fewer characters we have to type, the better.

**Comment by adam3smith** [comment]
yes, I agree. Having the ability to completely unambiguously point to a specific style would be the goal here. The highlighting is nice, but in my experience is still going to get missed by a good number of people.

**Comment by dstillman** [comment]
Yeah, I think we want to change the "View Source" on hover to "Link" and "Source", with the latter triggering `?q=id:apa`.

**Comment by adam3smith** [comment]
that's the *former* (i.e. "Link") triggering `?=id:apa`, right?

**Comment by dstillman** [comment]
Yes, sorry, reordered those after typing.

**Comment by rmzelle** [comment]
Yeah, that would be great. (maybe "Download" instead of "Source" would be clearer?)

**Comment by dstillman** [comment]
It's not a download, though.

**Comment by adam3smith** [comment]
yeah, source seems right to me. Download/install is what a regular click does, no?

**Comment by dstillman** [comment]
That's right.

**Comment by rmzelle** [comment]
What's the purpose of the source view, otherwise? As I understood it, it was added to add a way to access the style while suppressing the Zotero for Firefox "do you want to install this style" dialog. Wouldn't most people want to download it, in that case?

**Comment by dstillman** [comment]
The purpose of the source view is to view the source. I've clicked that link many times and never downloaded from it. You can download just by right-clicking on the main link. Doesn't make sense to call the thing a download that's specifically coded to show up in the browser pane.

**Comment by adam3smith** [comment]
Was going to write exact same thing as Dan. Using source view a lot, too, e.g. for documentation links.

**Comment by rmzelle** [comment]
Okay, never mind, then.

**Comment by rmzelle** [comment]
Thanks, Dan.

(others: it will get easier to get a direct link, but for now just fashioning URLs as https://www.zotero.org/styles?q=id:apa already works [super snappy, too!])

**Comment by dstillman** [comment]
This is now live.

**Comment by adam3smith** [comment]
works nicely, thanks!
