### ISSUE TITLE
vancouver / bmc-bioinformatics: DOI and Available from

### ISSUE THREAD

**Issue by sjackman** [zotero/styles-repo#39]
From the Submission Guidelines of BMC Bioinformatics
https://bmcbioinformatics.biomedcentral.com/submission-guidelines/preparing-your-manuscript/software-article

An article with a DOI should be cited like so (see Article within a journal by DOI):

Slifka MK, Whitton JL. Clinical implications of dysregulated cytokine production. Dig J Mol Med. 2000; doi:10.1007/s801090000086.

I'm instead seeing

Slifka MK, Whitton JL. Clinical implications of dysregulated cytokine production. Dig J Mol Med. 2000; Available from: https://doi.org/10.1007/s001090000086

My BibTex entries include both `DOI={…}` and `url={…}`. I'm using Pandoc 2.2.1 and pandoc-citeproc 0.14.3.1.

Is there a tweak that I can make to the CSL file to use the DOI rather than the URL?

**Comment by sjackman** [comment]
It'd be great of course if `doi:10.1007/s801090000086` were a hyperlink to https://doi.org/10.1007/s801090000086

**Comment by dstillman** [comment]
https://github.com/citation-style-language/styles/wiki/Requesting-Styles
