### ISSUE TITLE
Circulation Research journal style

### ISSUE THREAD

**Issue by jccucm** [zotero/styles-repo#41]
Hi everyone, 

I´ve adapted a Zootero Style for the Journal of the American Heart Association to the Circulation Research Journal. It only changes about the number of authors to be shown. However, I am not able to change the name of the style. I´m adding the file here to check if someone can do it and upload it to the Zootero repository. Thank you!

**Comment by dstillman** [comment]
This repository isn't for style development. See the CSL styles repo:

https://github.com/citation-style-language/styles
